### ISSUE TITLE
Possibly making the crate `#![no_std]`?

### ISSUE THREAD

**Issue by novacrazy** [Fluci/ply-rs#13]
Would need a replacement or update to `linked_hash_map`.

**Comment by Fluci** [comment]
Is it urgent for you? There might be a point in splitting it into a core and non-core part. I need to check that.

**Comment by novacrazy** [comment]
It's not. I ended up incorporating a couple additional crates into my model loading pipeline that use `std` anyway, so whatever. I was simply trying to keep everything as lightweight as possible. 

You can feel free to close this if you want.
